# -*- coding: utf-8 -*-
"""MPV 2 -  Análise de Dados e Boas Práticas - VERSÃO 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7XrkkHq9wf60FKQAX6X6vkdknUDTeKg

# MVP Análise de Dados e Boas Práticas

**Aluna:** Ana Nery Alves Daniel

**Matrícula:** 4052024002341

**Dataset:** [Microdados da Educação Superior 2023](https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/censo-da-educacao-superior) e [Municípios do Ceará segundo Regiões de Planejamento](https://www.ipece.ce.gov.br/regioes-de-planejamento/)

# Descrição do Problema

Baixo quantitativo de sedes administrativas de instituições de ensino superior (IES) da rede pública no estado do Ceará, bem como número reduzido de docentes com doutorado em exercício nessas instituições.

# Objetivo

Realizar levantamento de quais municípios do estado do Ceará têm baixo quantitativo ou ausência de sedes administrativa de instituições de ensino superior (IES), bem como identificar o número de docentes em exercício com nível de doutorado nessas sedes, identificando, ainda, o quantitativo desses docentes declarados pretos, com vistas a expandir políticas afirmativas para esse grupo e melhorar a distribuição de IES no referido estado.

Ao final do levantamento, será sugerida a ampliação de sede de instituições de ensino superior por *Região de Planejamento* do estado do Ceará*.

**Observação**:  **O foco deste levantamento não inclui unidades menores das instituições de ensino superior (polos). Portanto, considera-se IES neste levantamento somente as sedes administrativas das instituições de ensino superior no estado do Ceará.**
<br><br>
*_Região de Planejamento do estado do Ceará: Divisões territoriais criadas para organizar o planejamento e a implementação de políticas públicas. Classificação do Instituto de Pesquisa e Estratégia Econômica do Ceará - IPECE._

## Hipóteses do Problema


*   Concentração de Instituições de ensino superior da rede pública e de professores com doutorado na capital na capital do estado do Ceará em detrimento das demais regiões do estado.

*  Existência apenas de instituições de ensino da rede privada na maioria dos municípios do Ceará.

## Tipo de Problema

O problema explorado neste dataset não se classifica nem como supervisionado e nem como não supervisionado, uma vez que o conjunto de dados não possui classificação prévia dos dados (supervisionado) e não foram identificadas em levantamento inicial características necessárias para definir um padrão de comportamento para agrupar esses dados (não supervisionado), criando uma classificação. Nesse sentido, este trabalho irá focar na exploração e entendimento dos dados.

## Seleção de Dados

O dataset deste trabalho é composto por duas fontes de dados. A primeira fonte lista um conjunto de sedes de instituições de ensino superior no Brasil, obtidas do [Censo Inep de 2023](https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/censo-da-educacao-superior), e a segunda fonte lista os municípios do estado do Ceará por região de planejamento administrativo, sendo esse obtido do [Ipece](https://www.ipece.ce.gov.br/regioes-de-planejamento/).

Optou-se por filtrar e analisar somente os dados do estado do Ceará em razão da facilidade de acesso à lista de regiões de planejamento desse estado, o que não ocorreu com as demais regiões do país. Vale ressaltar que o Ipece fornece a lista de municípios classificada por região de planejamento, mas não fornece nenhum dos critérios utilizados para essa classificação.

## Atributos do Dataset

**Dataset Instituições de Ensino Superior (IES)**

Este dataset contém 101 sedes de instituições de ensino superior, sendo 94 da rede privada e 7 da rede pública. Os atributos dessas instituições utilizados nesta pesquisa estão descritos abaixo:

| Nome da coluna | Tipo | Tamanho | Descrição |
| -------- | ----- | ----- | ----------- |
| CO_IES | Num | 8 | Código único de identificação da IES |
| NO_MUNICIPIO_IES | Char | 150 | Nome do Município da sede administrativa ou reitoria da IES
| NO_IES | Char | 200 | Nome da IES
| SG_IES |Char | 20 | Sigla da IES
| SG_UF_IES |Char | 2 | Sigla da Unidade da Federação da sede administrativa ou reitoria da IES
| CO_MUNICIPIO_IES | Num | 7 | Código do município da sede administrativa da IES
| TIPO_REDE | Char | 7 | Tipo de rede de ensino (1. pública /2.privada)
| QT_DOC_TOTAL | Num | 8 | Quantidade total de docentes (em exercício e afastados)
| QT_DOC_EXE | Num | 8 | Quantidade total de docentes em exercício
| QT_DOC_EX_DOUT | Num | 8 | Quantidade de docentes em exercício com doutorado
| QT_DOC_EX_PRETA | Num | 8 | Quantidade de docentes em exercício - Cor/Raça preta

<br>

**Dataset Regiões de Planejamento do Ceará**

Este dataset contém 184 municípios divididos em 14 Regiões de Planejamento. Os atributos dessas instituições utilizados nesta pesquisa estão descritos abaixo:

| Nome da coluna | Tipo | Tamanho | Descrição |
| -------- | ----- | ----- | ----------- |
| CO_MUNICIPIO | Num| 7 | Código do município da sede administrativa da IES |
| NO_MUNICIPIO | Char | 150 | Nome do Município da sede administrativa ou reitoria da IES
| REG_PLA_CE | Char | 100 | Nome da região de planejamento do Ceará.

# Importação das Bibliotecas Necessárias e Carga de Dados

Esta seção consolida todas as importações de bibliotecas necessárias para a análise, visualização e pré-processamento dos dados, bem como o carregamento inicial do dataset Iris.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# carregamento do dataset instituições de ensino superior (ies)
url_ies = 'https://raw.githubusercontent.com/neryana/pos-ciencia-dados/refs/heads/main/modelagem%20vers%C3%A3o%203/MICRODADOS_ED_SUP_IES_2023.CSV%20-%20BRUTOS.csv'
df1 = pd.read_csv(url_ies)

# carregamento do dataset das regiões de planejamento do Ceará
url_regioes = 'https://raw.githubusercontent.com/neryana/pos-ciencia-dados/refs/heads/main/modelagem%20vers%C3%A3o%203/Lista_Regioes_Planejamento_Ceara.csv'
df1 = pd.read_csv(url_regioes)

import pandas as pd

# guardo o dataset ies em um dataframe
df = pd.read_csv(url_ies)

# primeiras linhas do dataframe ies
df.head()

import pandas as pd

# guardo o dataset regioes em um dataframe
df = pd.read_csv(url_regioes)

# primeiras linhas do dataframe ies
df.head()

# guardando o dataset regioes em um dataframe reorganizando em colunas
df = pd.read_csv(url_regioes, sep=';' )

# primeiras linhas do dataframe regioes agora organizado em colunas
df.head()

"""# Análise de Dados

Esta etapa traz uma visão geral dos dados obtidos dos dois datasets que irão compor a análise deste trabalho (Instituições de Ensino Superior e Regiões de Planejamento do Ceará) a partir dos quais será realizada filtragem dos dados, bem como outros tratamentos necessários para obter as informações indispensáveis para atingir o objetivo desta pesquisa.

## Total e Tipo das Instâncias

**Dataset Instituições de Ensino Superior**

Este dataset possui 2580 instâncias (observações) nas quais existem variáveis do tipo categórica, como as que definem o nome do município, estado e das sedes das instituições de ensino superior (IES); e numérica do tipo inteiro, como as que quantificam o total de docentes, de docentes por cor, bem como a variável ano.

**Dataset Regiões de Planejamento do Ceará**

Este dataset possui 184 instâncias (observações) somente com variáveis categóricas: nome do município, nome da região e código do município.
"""

import pandas as pd

# URL do dataset
url_ies = 'https://raw.githubusercontent.com/neryana/pos-ciencia-dados/refs/heads/main/modelagem%20vers%C3%A3o%203/MICRODADOS_ED_SUP_IES_2023.CSV%20-%20BRUTOS.csv'

# Carregar o dataset Instituições de Ensino Superior
df = pd.read_csv(url_ies)

# Obter o tipo de cada coluna Instituições de Ensino Superior
tipos = df.dtypes

# Obter o total de instâncias (linhas) Instituições de Ensino Superior
total_instancias = len(df)

print("Tipos de cada coluna:\n", tipos)
print("\nTotal de instâncias (linhas):", total_instancias)

import pandas as pd

# URL do dataset
url_regioes = 'https://raw.githubusercontent.com/neryana/pos-ciencia-dados/refs/heads/main/modelagem%20vers%C3%A3o%203/Lista_Regioes_Planejamento_Ceara.csv'

# Carregar o dataset Regiões de Planejamento do Ceará
df = pd.read_csv(url_regioes)

# Obter o tipo de cada coluna Regiões de Planejamento do Ceará
tipos = df.dtypes

# Obter o total de instâncias (linhas) Regiões de Planejamento do Ceará
total_instancias = len(df)

print("Tipos de cada coluna:\n", tipos)
print("\nTotal de instâncias (linhas):", total_instancias)

"""## Delimitando o dataset de Instituições de Ensino Superior

Na seção a seguir será realizada a filtragem do dataset das Instituições de Ensino Superior (IES) para retornar somente as instituições do estado do Ceará. Esse filtro será necessário uma vez que se busca saber a distribuição dessas IES por Região de Planejamento no estado do Ceará.
"""

import pandas as pd

# URL do arquivo CSV
url_ies = 'https://raw.githubusercontent.com/neryana/pos-ciencia-dados/refs/heads/main/modelagem%20vers%C3%A3o%203/MICRODADOS_ED_SUP_IES_2023.CSV%20-%20BRUTOS.csv'

# Lista de colunas desejadas
colunas = [
    'CO_IES',
    'NO_IES',
    'SG_IES',
    'SG_UF_IES',
    'NO_MUNICIPIO_IES',
    'CO_MUNICIPIO_IES',
    'TP_REDE',
    'QT_DOC_TOTAL',
    'QT_DOC_EXE',
    'QT_DOC_EX_DOUT',
    'QT_DOC_EX_PRETA'
]

# 1. Leitura apenas das colunas desejadas
df = pd.read_csv(url_ies, usecols=colunas)

# 2. Filtrar linhas onde SG_UF_IES == 'CE'
df_ce = df[df['SG_UF_IES'] == 'CE'].copy()

# 3. Substituir valores da coluna TP_REDE
df_ce['TP_REDE'] = df_ce['TP_REDE'].map({1: 'pública', 2: 'privada'})

# 4. Organizar display como tabela
df_ce.reset_index(drop=True, inplace=True)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# Exibe tabela final formatada
print(df_ce)

nome_arquivo = 'IES_CE_filtrado.csv'
df_ce.to_csv(nome_arquivo, index=False, encoding='utf-8-sig')
print(f"\nArquivo salvo como: {'IES_CE_filtrado.csv'}")

# Permitir download do novo cvs, com os dados filtrados.
from google.colab import files
files.download('IES_CE_filtrado.csv')

import pandas as pd

# Carrega o novo cvs com os dados filtrados, o qual foi salvo no github e será chamado pela URL abaixo
df = pd.read_csv('https://raw.githubusercontent.com/neryana/pos-ciencia-dados/refs/heads/main/modelagem%20vers%C3%A3o%203/IES_CE_filtrado.csv')

ies_filtrado = pd.read_csv('https://raw.githubusercontent.com/neryana/pos-ciencia-dados/refs/heads/main/modelagem%20vers%C3%A3o%203/IES_CE_filtrado.csv')

import pandas as pd
import matplotlib.pyplot as plt

# Carregar o arquivo CSV salvo localmente no ambiente do Colab
df = ies_filtrado.copy()

# Contar o número de instituições distintas por município (SG_IES diferentes)
municipios_menos_ies = (
    df.groupby('NO_MUNICIPIO_IES')['SG_IES']
      .nunique()
      .sort_values(ascending=True)
      .head(10)
)

# Criar gráfico
plt.figure(figsize=(10, 6))
bars = plt.bar(municipios_menos_ies.index.astype(str), municipios_menos_ies.values, color='skyblue')

# Adicionar valores dentro das barras
for bar in bars:
    yval = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,  # Posição no centro da barra
        yval / 2,                           # Meio da altura da barra
        int(yval),                          # Valor a ser exibido
        ha='center', va='center', fontsize=9, color='black'
    )

# Personalizar o gráfico
plt.xlabel('Nome do Município (IES)')
plt.ylabel('Quantidade de Instituições')
plt.title('10 Municípios do CE com Menor Número de Instituições de Ensino Superior')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""O gráfico de barras acima exibe os 10 municípios com menor quantidade de instituições de ensino superior (IES) no Ceará. No entanto, o dataset usado para o gráfico não traz a informação sobre a qual região de planejamento do estado esses municípios pertecem. Essa informação é importante, pois, em médio prazo, é mais viável criar novas IES por região de planejamento do que para cada um desses municípios. Assim, para saber a carência de IES por região de planejamento, será necessário buscar informações em um segundo dataset, o das regiões de planejamento.

A consulta abaixo exibe a qual região de planejamento pertecem as cidades de Cascavel e Icó, que vimos não ter nenhuma instituição de ensino.
"""

import pandas as pd

# Carregar o dataset regiões com separador correto
regioes = pd.read_csv(
    'https://raw.githubusercontent.com/neryana/pos-ciencia-dados/refs/heads/main/modelagem%20vers%C3%A3o%203/Lista_Regioes_Planejamento_Ceara.csv',
    sep=';'
)

# Limpar espaços extras nas colunas e nos dados da coluna 'Nome do município'
regioes.columns = regioes.columns.str.strip()
regioes['Nome do município'] = regioes['Nome do município'].str.strip()

# Filtrar apenas os municípios Cascavel e Icó
municipios_interesse = regioes[regioes['Nome do município'].isin(['Cascavel', 'Icó'])]

# Selecionar as colunas desejadas e exibir
resultado = municipios_interesse[['Nome do município', 'Região de Planejamento']]

print(resultado)

import pandas as pd

# Carregar os dados
ies = pd.read_csv(
    'https://raw.githubusercontent.com/neryana/pos-ciencia-dados/refs/heads/main/modelagem%20vers%C3%A3o%203/IES_CE_filtrado.csv'
)
regioes = pd.read_csv(
    'https://raw.githubusercontent.com/neryana/pos-ciencia-dados/refs/heads/main/modelagem%20vers%C3%A3o%203/Lista_Regioes_Planejamento_Ceara.csv',
    sep=';'
)

# Limpar espaços nos nomes das colunas
ies.columns = ies.columns.str.strip()
regioes.columns = regioes.columns.str.strip()

# Mesclar os datasets
df = pd.merge(
    ies,
    regioes,
    how='left',
    left_on='CO_MUNICIPIO_IES',
    right_on='CO_MUNICIPIO'
)

# Contar SG_IES únicos por Região de Planejamento
resultado = df.groupby('Região de Planejamento')['SG_IES'].nunique().reset_index()
resultado.columns = ['Região de Planejamento', 'Quantidade_SG_IES']

# Exibir apenas as duas colunas desejadas
print(resultado[['Região de Planejamento', 'Quantidade_SG_IES']])

media_instituicoes = df.groupby('NO_MUNICIPIO_IES')['SG_IES'].nunique().mean()
print(f'Média de instituições por município: {media_instituicoes:.2f}')

"""## Estatísticas Descritivas:

Como dito inicialmente, este MVP traz uma pesquisa que utilizou dois datasets como base. O dataset com a lista somente os municípios do Ceará por Região de Planejamento e um segundo dataset com a lista de Instituições de Ensino Superior, de onde obtemos as instituições por município e, também, de onde obteremos a quantidade de docentes declarados pretos nessas instituições. Diante disso, a estatística descritiva será analisada em 2 blocos, um para cada dataset.

<br>

###Bloco 1: Estatística Descritiva - Instituições de Ensino Superior no Ceará por Regiões de Planejamento


O resumo estatístico gerado abaixo evidencia a má distribuição de instituições de ensino superior (IES) no estado do Ceará, apontando extremos entre 1 e 40 e um desvio padrão alto, de aproximadamente 10, indicando alta dispersão por afastar-se da média, que é 5.

"""

import pandas as pd

# Criar o DataFrame com os dados fornecidos
data = {
    'Região de Planejamento': [
        'Cariri', 'Centro Sul', 'Grande Fortaleza', 'Litoral Leste',
        'Litoral Norte', 'Litoral Oeste / Vale do Curu', 'Maciço de Baturité',
        'Serra da Ibiapaba', 'Sertão Central', 'Sertão de Canindé',
        'Sertão de Sobral', 'Sertão dos Crateús', 'Sertão dos Inhamuns',
        'Vale do Jaguaribe'
    ],
    'Quantidade_SG_IES': [9, 2, 40, 1, 1, 1, 2, 5, 6, 1, 5, 2, 1, 2]
}

df = pd.DataFrame(data)

# Obter estatísticas descritivas e nomear a série
estatisticas = df['Quantidade_SG_IES'].describe()
estatisticas.name = 'Estatísticas: Quantidade_SG_IES'

# Exibir com nome no topo
print(estatisticas.to_frame())



import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Dados fornecidos
data = {
    'Região de Planejamento': [
        'Cariri', 'Centro Sul', 'Grande Fortaleza', 'Litoral Leste',
        'Litoral Norte', 'Litoral Oeste / Vale do Curu', 'Maciço de Baturité',
        'Serra da Ibiapaba', 'Sertão Central', 'Sertão de Canindé',
        'Sertão de Sobral', 'Sertão dos Crateús', 'Sertão dos Inhamuns',
        'Vale do Jaguaribe'
    ],
    'Quantidade de IES': [9, 2, 40, 1, 1, 1, 2, 5, 6, 1, 5, 2, 1, 2]
}

# Criar DataFrame
df = pd.DataFrame(data)

# Criar a figura
plt.figure(figsize=(8, 5))
sns.boxplot(x=df['Quantidade de IES'], color='lightgreen')
plt.title('Boxplot da Quantidade de IES por Região')
plt.xlabel('Quantidade de IES')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Dados fornecidos
data = {
    'Região de Planejamento': [
        'Cariri', 'Centro Sul', 'Grande Fortaleza', 'Litoral Leste',
        'Litoral Norte', 'Litoral Oeste / Vale do Curu', 'Maciço de Baturité',
        'Serra da Ibiapaba', 'Sertão Central', 'Sertão de Canindé',
        'Sertão de Sobral', 'Sertão dos Crateús', 'Sertão dos Inhamuns',
        'Vale do Jaguaribe'
    ],
    'Quantidade de IES': [9, 2, 40, 1, 1, 1, 2, 5, 6, 1, 5, 2, 1, 2]
}

# Criar DataFrame
df = pd.DataFrame(data)

# Criar a figura
plt.figure(figsize=(8, 5))
sns.histplot(data=df, x='Quantidade de IES', bins=10, color='lightblue', edgecolor='black')
plt.title('Histograma da Quantidade de IES por Região')
plt.xlabel('Quantidade de IES')
plt.ylabel('Frequência')
plt.grid(True)
plt.show()

# estatísticas descritivas básicas do dataset ignorando as colunas de código, pois não têm sentido estatístico.

# Selecionar apenas as colunas numéricas de interesse (ignorando os códigos)
colunas_numericas = [
    'QT_DOC_TOTAL',
    'QT_DOC_EXE',
    'QT_DOC_EX_DOUT',
    'QT_DOC_EX_PRETA'
]

# Gerar estatísticas descritivas
df[colunas_numericas].describe()

"""### Média

A média é uma medida de tendência central que representa o valor típico ou o ponto de equilíbrio de um conjunto de dados. É calculada somando-se todos os valores e dividindo-se pelo número total de observações. É sensível a valores extremos (outliers).
"""

# média dos atributos numéricos do dataset
df.describe().loc['mean']

# Qual gráfico seria interessante usar pra mostrar a média?

"""### Desvio Padrão

O desvio padrão é uma medida de dispersão que quantifica a quantidade de variação ou dispersão de um conjunto de valores. Um desvio padrão baixo indica que os pontos de dados tendem a estar próximos da média do conjunto, enquanto um desvio padrão alto indica que os pontos de dados estão espalhados por uma faixa maior de valores. Ele é a raiz quadrada da variância.
"""

# desvio padrão dos atributos numéricos do dataset
df.describe().loc['std']

# Qual gráfico seria interessante usar pra mostrar o desvio padrão?

"""## Histograma

A distribuição de dados descreve como os valores de uma variável se espalham, ou seja, a frequência com que diferentes valores ocorrem. Entender a distribuição é crucial na análise de dados, pois revela padrões, tendências centrais, dispersão e a presença de valores atípicos (outliers). O histograma é uma ferramenta visual fundamental para representar essa distribuição, mostrando a forma dos dados, se são simétricos ou assimétricos, unimodais ou multimodais.

### *sepal length*

Alguma curiosidade ou fato importante sobre o atributo que estamos olhando a distribuição?
"""

plt.figure(figsize=(8, 6))
# Histograma do comprimento da sépala (um dos atributos)
sns.histplot(df['sepal length (cm)'], kde=True)
plt.title('Distribuição do Comprimento da Sépala')
plt.xlabel('Comprimento da Sépala (cm)')
plt.ylabel('Frequência')
plt.show()

"""O histograma mostra a distribuição do comprimento da sépala. A curva de densidade estimada (KDE) nos indica que a distribuição parece bimodal ou multimodal, indicando que as espécies podem ter comprimentos de sépalas diferentes.

### *sepal width*

Alguma curiosidade ou fato importante sobre o atributo que estamos olhando a distribuição?
"""

plt.figure(figsize=(8, 6))
# Histograma do comprimento da sépala (um dos atributos)
sns.histplot(df['sepal width (cm)'], kde=True)
plt.title('Distribuição da Largura da Sépala')
plt.xlabel('Largura da Sépala (cm)')
plt.ylabel('Frequência')
plt.show()

"""Quais impressões você tem sobre a distribuição do atributo 'sepal width'?

## Boxplot

Para entender as diferenças entre as espécies, devemos olhar como se comportam os valores quando agrupadas por espécie. Isso nos permite comparar a média, mediana e desvio padrão de cada característica para Iris setosa, Iris versicolor e Iris virginica, além de visualizar suas distribuições por meio de boxplots.
"""

# Estatísticas descritivas agrupadas por espécie
df.groupby('species').describe()

"""### *petal length* por Espécie

"""

# Boxplot do comprimento da pétala por espécie
plt.figure(figsize=(10, 6))
sns.boxplot(x='species', y='petal length (cm)', data=df)
plt.title('Comprimento da Pétala por Espécie')
plt.xlabel('Espécie')
plt.ylabel('Comprimento da Pétala (cm)')
plt.show()

"""O boxplot do comprimento da pétala por espécie demonstra claramente que a Iris setosa tem pétalas significativamente mais curtas do que as outras duas espécies. Há uma sobreposição entre Iris versicolor e Iris virginica, mas as medianas e as caixas indicam uma distinção.

### *petal width* por Espécie
"""

# Boxplot do comprimento da pétala por espécie
plt.figure(figsize=(10, 6))
sns.boxplot(x='species', y='petal width (cm)', data=df)
plt.title('Largura da Pétala por Espécie')
plt.xlabel('Espécie')
plt.ylabel('Largura da Pétala (cm)')
plt.show()

"""Quais impressões o boxplot trouxe?

## Matriz de Correlação

A matriz de correlação mede a força e a direção de uma relação linear que os atributos numéricos das espécies podem ter. Valores próximos a 1 indicam uma forte correlação positiva, -1 uma forte correlação negativa, e 0 ausência de correlação linear.
"""

# Matriz de correlação
print("\nMatriz de Correlação:")
df.iloc[:, :4].corr()

plt.figure(figsize=(8, 6))
# mapa de calor das variáveis numéricas
sns.heatmap(df.iloc[:, :4].corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Matriz de Correlação das Características Numéricas do Iris Dataset')
plt.show()

"""O mapa de calor da matriz de correlação revela fortes correlações positivas entre *petal length* e *petal width*, bem como entre *sepal length* e *petal length*/*petal width*. Isso sugere que essas características se movem juntas, o que é útil para a seleção de características.

# Pré-Processamento de Dados

O pré-processamento de dados é uma etapa crucial para preparar os dados para modelagem, garantindo que estejam no formato correto e otimizados para o desempenho do algoritmo.
"""

# Separar features (X) e target (y)
X = df.drop('species', axis=1)
y = df['species']

# Dividir os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

print(f"Dimensões de X_train: {X_train.shape}")
print(f"Dimensões de X_test: {X_test.shape}")
print(f"Dimensões de y_train: {y_train.shape}")
print(f"Dimensões de y_test: {y_test.shape}")

"""## Normalização

A normalização escala os dados para um intervalo fixo, geralmente entre 0 e 1. É útil quando o algoritmo de machine learning assume que as características estão em uma escala semelhante.


"""

# Inicializar o MinMaxScaler
scaler_norm = MinMaxScaler()

# Aprende min e max APENAS de X_train
scaler_norm.fit(X_train)
X_train_normalized = scaler_norm.transform(X_train)
# Usa a média e o desvio padrão aprendidos de X_train
X_test_normalized = scaler_norm.transform(X_test)

# Exibir as primeiras linhas dos dados normalizados (como DataFrame para melhor visualização)
df_normalized = pd.DataFrame(X_train_normalized, columns=X_train.columns)

print("\nPrimeiras 5 linhas dos dados normalizados (treino):")
print(df_normalized.head())

# Visualização da distribuição após a normalização (exemplo para uma característica)
plt.figure(figsize=(8, 6))
sns.histplot(df_normalized['sepal length (cm)'], kde=True)
plt.title('Distribuição do Comprimento da Sépala (Normalizado)')
plt.xlabel('Comprimento da Sépala Normalizado')
plt.ylabel('Frequência')
plt.show()

"""O histograma de *sepal length* após a normalização mostra que os valores foram escalados para o intervalo de 0 a 1, mantendo a forma da distribuição original.

## Padronização

A padronização (ou Z-score scaling) transforma os dados para ter média 0 e desvio padrão 1. É útil para algoritmos que são sensíveis à escala das características, como SVMs ou redes neurais.
"""

# Inicializar o StandardScaler
scaler_std = StandardScaler()

# Aprende média e desvio padrão APENAS de X_train
scaler_std.fit(X_train)
X_train_standardized = scaler_std.transform(X_train)
# Usa a média e o desvio padrão aprendidos de X_train
X_test_standardized = scaler_std.transform(X_test)

# Exibir as primeiras linhas dos dados padronizados (como DataFrame para melhor visualização)
df_standardized = pd.DataFrame(X_train_standardized, columns=X_train.columns)

print("\nPrimeiras 5 linhas dos dados padronizados (treino):")
print(df_standardized.head())

# Visualização da distribuição após a padronização (exemplo para uma característica)
plt.figure(figsize=(8, 6))
sns.histplot(df_standardized['sepal length (cm)'], kde=True)
plt.title('Distribuição do Comprimento da Sépala (Padronizado)')
plt.xlabel('Comprimento da Sépala Padronizado')
plt.ylabel('Frequência')
plt.show()

"""O histograma de *sepal length* após a padronização mostra que os valores foram transformados para ter uma média próxima de zero e um desvio padrão de um, centralizando a distribuição.

## Tratamento de Valores Nulos

O dataset Iris original não possui valores nulos. No entanto, o tratamento de valores nulos é crucial e pode envolver imputação (preenchimento com média, mediana, moda) ou remoção de linhas/colunas.
"""

# Verificar a presença de valores nulos no dataset original
print("Valores nulos no dataset Iris:")
df.isnull().sum()

"""## Outras Transformações e Etapas de Pré-Processamento

Outras etapas de pré-processamento incluem a seleção de características, redução de dimensionalidade (como PCA) ou criação de novas características (feature engineering). O que você faria a mais?

# Conclusão

A análise e pré-processamento do dataset Iris demonstram a importância de entender a estrutura dos dados antes da modelagem. O dataset é limpo e balanceado, com características numéricas bem definidas que permitem uma clara separação entre as espécies, especialmente a Iris setosa. A análise exploratória revelou correlações importantes entre as características e a eficácia de visualizações como boxplots para distinguir as classes. As etapas de normalização e padronização são fundamentais para preparar os dados para diversos algoritmos de aprendizado de máquina, garantindo que o modelo possa aprender eficientemente com as relações presentes nos dados.

As três hipóteses levantadas foram validadas:

1.   *As diferentes espécies de Íris podem ser distinguidas com base nas medições de suas sépalas e pétalas?* Sim, dado as análises que fizemos no boxplot, observamos um comportamento muito claro e distinto.

2.   *Existe uma correlação entre comprimento da pétala e largura da pétala?* Existe forte correlação entre os atributos *petal length* e *petal width*.

3.   *A espécie Iris setosa é mais facilmente separável das outras duas espécies?* Sim, devido às suas características distintas de menor comprimento e largura da pétala.
"""